version: '3'
services:
 bitbucket:
  image: "atlassian/bitbucket-server:5.0"
  container_name: bitbucket
  restart: always
  ports:
   - "7990:7990"
   - "7999:7999"
  environment:
   - BITBUCKET_HOME=/var/atlassian/application-data/bitbucket/
  volumes:
   - bitbucketData:/var/atlassian/application-data/bitbucket
 db:
  image: postgres:9.6
  container_name: bitbucket-database
  restart: always
  ports:
   - "1234:5432"
  environment:
   POSTGRES_PASSWORD: 8462368
   POSTGRES_USER: postgres
   POSTGRES_DB: postgres
   PGDATA: /var/lib/postgresql/data/pgdata
  volumes:
   - bitbucketDbVolume:/var/lib/postgresql/data
volumes:
 bitbucketData:
   name: bitbucketData
 bitbucketDbVolume:
   name: bitbucketDbVolume